=== SantamariaLab/NeuroManager/NMSessionML/NMSessMLMATLAB.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="ParamToken">
		<xs:restriction base="xs:token">
			<xs:pattern value="\S+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="id" type="xs:ID"/>
	<xs:element name="simtype" type="xs:NMTOKEN"/>
	<xs:element name="param01" type="ParamToken"/>
	<xs:element name="param02" type="ParamToken"/>
	<xs:element name="param03" type="ParamToken"/>
	<xs:element name="param04" type="ParamToken"/>
	<xs:element name="param05" type="ParamToken"/>
	<xs:element name="param06" type="ParamToken"/>
	<xs:element name="param07" type="ParamToken"/>
	<xs:element name="param08" type="ParamToken"/>
	<xs:element name="param09" type="ParamToken"/>
	<xs:element name="param10" type="ParamToken"/>
	<xs:element name="comment" type="xs:normalizedString"/>
	<xs:attribute name="notifications" type="xs:boolean"/>
	
	<xs:element name="commentline">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="comment" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="userstaticdatafilepath" type="xs:string"/>      <!-- May not be best -->
	<xs:element name="customdir" type="xs:string"/>      <!-- May not be best -->
	<xs:element name="modeldir" type="xs:string"/>       <!-- May not be best -->
	<xs:element name="simspecdir" type="xs:string"/>     <!-- May not be best -->
	<xs:element name="resultsdir" type="xs:string"/>     <!-- May not be best -->
	<xs:element name="addlsearchpath" type="xs:string"/> <!-- May not be best -->
	
	<!-- Locations of Session stuff with respect to install directory -->
	<xs:element name="locationinfo">
		<xs:complexType>
			<xs:sequence>		
				<!-- Absolute pathname -->
				<xs:element ref="userstaticdatafilepath" minOccurs="1" maxOccurs="1"/>
				<!-- Absolute pathname -->
				<xs:element ref="customdir" minOccurs="1" maxOccurs="1"/>
				<!-- Absolute pathname -->
				<xs:element ref="modeldir" minOccurs="0" maxOccurs="1"/>
				<!-- Absolute pathname -->
				<xs:element ref="simspecdir" minOccurs="1" maxOccurs="1"/>
				<!-- Absolute pathname -->
				<xs:element ref="resultsdir" minOccurs="1" maxOccurs="1"/>
				<!-- Absolute pathnames -->
				<xs:element ref="addlsearchpath" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="machinetype" type="xs:NMTOKEN"/>
	<xs:element name="numsimulators" type="xs:nonNegativeInteger"/> 
	<xs:element name="numwisps" type="xs:nonNegativeInteger"/> 
	<xs:element name="workdir" type="xs:anyURI"/>    <!-- may need adjustment -->
	<xs:element name="infofile" type="xs:anyURI"/>    <!-- may need adjustment -->
	<xs:element name="queue" type="xs:string"/> <!-- May not be best -->
	<xs:element name="wispnameroot" type="xs:string"/> <!-- May not be best -->
	
	<!-- in the hh:mm:ss format used by SLURM -->
	<xs:attribute name="wallclocktime">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[0-9][0-9]:[0-5][0-9]:[0-5][0-9]"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:element name="compilemachine">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="infofile" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>	
		</xs:complexType>
	</xs:element>
	
	<xs:element name="standaloneserver">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="infofile" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="numsimulators" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="workdir" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>	
		</xs:complexType>
	</xs:element>
	
	<xs:element name="cloudserver">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="infofile" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="numsimulators" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="workdir" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>	
		</xs:complexType>
	</xs:element>
	
	<xs:element name="wispset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="numwisps" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="wispnameroot" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="infofile" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="numsimulators" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="workdir" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>	
		</xs:complexType>
	</xs:element>
	
	<xs:element name="cluster">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="infofile" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="queue" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="numsimulators" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="workdir" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>	
			<xs:attribute ref="wallclocktime" use="optional"/>
		</xs:complexType>
	</xs:element>

	
	<xs:attribute name="singlemachine" type="xs:boolean" default="false"/>
	<xs:attribute name="usedualkey" type="xs:boolean" default="false"/>
	<xs:attribute name="polldelay" type="xs:positiveInteger" default="20"/>
	
	<xs:element name="machineset">
		<xs:complexType>
			<xs:sequence> 
				<xs:element ref="compilemachine" minOccurs="1" maxOccurs="1"/>
				<xs:choice  minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="standaloneserver" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="cloudserver" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="wispset" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="cluster" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute ref="singlemachine"/>
			<xs:attribute ref="usedualkey"/>
			<xs:attribute ref="polldelay" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sessionscript">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="locationinfo" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="machineset" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>		
		</xs:complexType>
	</xs:element>
	
	<xs:element name="simdef">
		<xs:complexType>
			<xs:sequence>		
				<xs:element ref="commentline" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="id" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="param01" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param02" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param03" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param04" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param05" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param06" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param07" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param08" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param09" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="param10" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute ref="notifications"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="simset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="simtype" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="commentline" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="simdef" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="notificationModes">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="EMAIL"/>
			<xs:enumeration value="TEXT"/>
			<xs:enumeration value="NONE"/>
			<xs:enumeration value="BOTH"/>
			<xs:enumeration value="OFF"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:attribute name="notificationmode" 
		type="notificationModes" 
		default="OFF"/>

	<xs:element name="nmsession">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="simset" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="sessionscript" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute ref="notificationmode" use="required"/>
			<!-- defaults weren't working for me for some reason so I require use. -->
			<xs:attribute name="logecho" type="xs:boolean" use="required"/>
			<xs:attribute name="showwebpage" type="xs:boolean" use="required"/>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SantamariaLab/NeuroManager/NeurSim/MiyashoMOD/KhStudy/NMSessionML03.xml
<?xml version="1.0" encoding="UTF-8"?>
<nmsession xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="../../NMSessionMLDev/NMSessMLMATLAB.xsd"
		   notificationmode="NONE"
		   logecho="true"
		   showwebpage="true"
		   id="NMSessionML03">
		   
	<simset>
		<id>NMSessionML03SS</id>
		<simtype>SIM_NEUR_PURKINJE_MIYASHO2001_KH</simtype>
		<commentline>
			<comment>cmd    id            curr  vinit delay stimdur tstep tstop   rcdintvl Kh_soma  Kh_smooth Kh_spiny</comment>
		</commentline>
		<simdef notifications="true">
			<id>KhStudyneg0800A</id> 
			<param01>-0.80</param01>	
			<param02>-65.0</param02>
			<param03>20.0</param03>
			<param04>400.0</param04>
			<param05>0.025</param05>
			<param06>1000.0</param06>
			<param07>0.1</param07>
			<param08>0.0005</param08>
			<param09>0.0000</param09>
			<param10>0.0000</param10>
		</simdef>
		<simdef notifications="true">
			<id>KhStudyneg0600A</id>
			<param01>-0.60</param01>	
			<param02>-65.0</param02>
			<param03>20.0</param03>
			<param04>400.0</param04>
			<param05>0.025</param05>
			<param06>1000.0</param06>
			<param07>0.1</param07>
			<param08>0.0005</param08>
			<param09>0.0000</param09>
			<param10>0.0000</param10>
		</simdef>
		<simdef notifications="true">
			<id>KhStudyneg0400A</id>
			<param01>-0.40</param01>	
			<param02>-65.0</param02>
			<param03>20.0</param03>
			<param04>400.0</param04>
			<param05>0.025</param05>
			<param06>1000.0</param06>
			<param07>0.1</param07>
			<param08>0.0005</param08>
			<param09>0.0000</param09>
			<param10>0.0000</param10>
		</simdef>
		<simdef notifications="true">
			<id>KhStudyneg0200A</id>
			<param01>-0.20</param01>	
			<param02>-65.0</param02>
			<param03>20.0</param03>
			<param04>400.0</param04>
			<param05>0.025</param05>
			<param06>1000.0</param06>
			<param07>0.1</param07>
			<param08>0.0005</param08>
			<param09>0.0000</param09>
			<param10>0.0000</param10>
		</simdef>
		<simdef notifications="true">
			<id>KhStudypos0000A</id>
			<param01>-0.00</param01>	
			<param02>-65.0</param02>
			<param03>20.0</param03>
			<param04>400.0</param04>
			<param05>0.025</param05>
			<param06>1000.0</param06>
			<param07>0.1</param07>
			<param08>0.0005</param08>
			<param09>0.0000</param09>
			<param10>0.0000</param10>
		</simdef>
		<simdef notifications="true">
			<id>KhStudypos0200A</id>
			<param01>0.20</param01>	
			<param02>-65.0</param02>
			<param03>20.0</param03>
			<param04>400.0</param04>
			<param05>0.025</param05>
			<param06>1000.0</param06>
			<param07>0.1</param07>
			<param08>0.0005</param08>
			<param09>0.0000</param09>
			<param10>0.0000</param10>
		</simdef>
		<simdef notifications="true">
			<id>KhStudypos0400A</id>
			<param01>0.40</param01>	
			<param02>-65.0</param02>
			<param03>20.0</param03>
			<param04>400.0</param04>
			<param05>0.025</param05>
			<param06>1000.0</param06>
			<param07>0.1</param07>
			<param08>0.0005</param08>
			<param09>0.0000</param09>
			<param10>0.0000</param10>
		</simdef>
	</simset>
	
	<sessionscript>
		<locationinfo>
			<userinfo>
				myNMStaticData
			</userinfo>
			<customdir>
				NeurSim/MiyashoMOD/KhStudy
			</customdir>
			<modeldir>
				NeurSim/MiyashoMOD
			</modeldir>
			<resultsdir>
				NeurSim/MiyashoMOD/KhStudy
			</resultsdir>
			<!-- The choice of absolute paths here is under debate -->
			<addlsearchpath>YOUR_ABSOLUTE_MiyashoMOD_DIRECTORY_GOES_HERE
			</addlsearchpath>
			<addlsearchpath>YOUR_ABSOLUTE_NeurSim_DIRECTORY_GOES_HERE
			</addlsearchpath>
		</locationinfo>
		
		<machineset singlemachine="false" usedualkey="true" polldelay="21">
			<machine>
				<machinetype>MYSERVER01</machinetype>
				<numsimulators>2</numsimulators>
				<workdir>MYSERVER01_WORK_DIRECTORY_GOES_HERE</workdir>
			</machine>
			<machine>
				<machinetype>MYSERVER02</machinetype>
				<numsimulators>2</numsimulators>
				<workdir>MYSERVER02_WORK_DIRECTORY_GOES_HERE</workdir>
			</machine>
			<machine>
				<machinetype>SGECLUSTERQUEUE01</machinetype>
				<numsimulators>2</numsimulators>
				<workdir>SGECLUSTERQUEUE01_WORK_DIRECTORY_GOES_HERE</workdir>
			</machine>
			<machine>
				<machinetype>SGECLUSTERQUEUE02</machinetype>
				<numsimulators>1</numsimulators>
				<workdir>SGECLUSTERQUEUE02_WORK_DIRECTORY_GOES_HERE</workdir>
			</machine>
		</machineset>
	</sessionscript>
	
</nmsession>

=== SantamariaLab/NeuroManager/NeurSim/SimpleSpike02A/NMSessionML02.xml
<?xml version="1.0" encoding="UTF-8"?>
<nmsession xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="../../NMSessionMLDev/NMSessMLMATLAB.xsd"
		   notificationmode="NONE"
		   logecho="true"
		   showwebpage="true"
		   id="NMSessionML02">

<simset>
		<id>NMSessionML02SS</id>
		<simtype>SIM_NEURON_SIMPLESPIKE02A</simtype>
		<commentline>
			<comment>In SimpleSpike02, we are manipulating our three input variables, but using the </comment>
		</commentline>
		<commentline>
			<comment>model files found in the Example01 directory.  We are doing a parameter sweep</comment>
		</commentline>
		<commentline>
			<comment>of input current and change up duration midway for illustration.</comment>
		</commentline>
		<commentline>
			<comment>      ID	         Current Duration  Input_Leak_gl</comment>
		</commentline>
		<simdef notifications="true">
			<id>Simulation01</id> 
			<param01>1</param01>	
			<param02>100</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation02</id>
			<param01>2</param01>	
			<param02>100</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation03</id>
			<param01>3</param01>	
			<param02>100</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation04</id>
			<param01>4</param01>	
			<param02>100</param02>
			<param03>1e-4</param03>
		</simdef>
		
		<simdef notifications="false">
			<id>Simulation05</id>
			<param01>5</param01>	
			<param02>100</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation06</id>
			<param01>6</param01>	
			<param02>150</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation07</id>
			<param01>7</param01>	
			<param02>150</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation08</id>
			<param01>8</param01>	
			<param02>150</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation09</id>
			<param01>9</param01>	
			<param02>150</param02>
			<param03>1e-4</param03>
		</simdef>
		<simdef notifications="false">
			<id>Simulation10</id>
			<param01>10</param01>	
			<param02>150</param02>
			<param03>1e-4</param03>
		</simdef>
	</simset>
	
	<sessionscript>
		<locationinfo>
			<userinfo>
				myNMStaticData
			</userinfo>
			<customdir>
				NeurSim/SimpleSpike02A
			</customdir>
			<modeldir>
				NeurSim/SimpleSpike01
			</modeldir>
			<resultsdir>
				NeurSim/SimpleSpike02A
			</resultsdir>
		</locationinfo>
		
		<machineset singlemachine="false" usedualkey="true" polldelay="21">
			<machine>
				<machinetype>MYSERVER01</machinetype>
				<numsimulators>4</numsimulators>
				<workdir>MYSERVER01_WORK_DIRECTORY_GOES_HERE</workdir>
			</machine>
			<machine>
				<machinetype>MYSERVER02</machinetype>
				<numsimulators>0</numsimulators>
				<workdir>MYSERVER02_WORK_DIRECTORY_GOES_HERE</workdir>
			</machine>
			<machine>
				<machinetype>MYSGECLUSTERQUEUE</machinetype>
				<numsimulators>4</numsimulators>
				<workdir>MYSGECLUSTERQUEUE_WORK_DIRECTORY_GOES_HERE</workdir>
			</machine>
		</machineset>
	</sessionscript>
	
</nmsession>

=== SantamariaLab/NeuroManager/SineSim/NMSessionML01.xml
<?xml version="1.0" encoding="UTF-8"?>
<nmsession xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="../NMSessionMLDev/NMSessMLMATLAB.xsd"
		   notificationmode="NONE"
		   logecho="true"
		   showwebpage="true"
		   id="NMSessionML01">
	
	<simset>
		<id>NMSessionML01</id>
		<simtype>SIM_SINESIM</simtype>
		<commentline>
			<comment>Each of the following is a separate simulation</comment>
		</commentline>
		<commentline>
			<comment>                    Param01 Param02</comment>
		</commentline>
		<simdef notifications="true">
			<id>SineSimRun01</id> 
			<param01>3.0e+0</param01>	
			<param02>2.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<id>SineSimRun02</id>
			<param01>6.0e+0</param01>
			<param02>1.0e+0</param02>
		</simdef>
        <simdef notifications="false">
			<id>SineSimRun03</id>
			<param01>9.0e+0</param01>
			<param02>1.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<commentline>
				<comment>Deliberate error in Run 4</comment>
			</commentline>
			<id>SineSimRun04</id>
			<param01>3.re+0</param01>
			<param02>1.0e+0</param02>
		</simdef>
		
		<simdef notifications="false">
			<id>SineSimRun05</id>
			<param01>3.0e+0</param01>
			<param02>3.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<id>SineSimRun06</id>
			<param01>3.0e+0</param01>
			<param02>4.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<id>SineSimRun07</id>
			<param01>3.0e+0</param01>
			<param02>5.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<id>SineSimRun08</id>
			<param01>3.0e+0</param01>
			<param02>6.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<id>SineSimRun09</id>
			<param01>3.0e+0</param01>
			<param02>7.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<id>SineSimRun10</id>
			<param01>3.0e+0</param01>
			<param02>8.0e+0</param02>
		</simdef>
		<simdef notifications="false">
			<id>SineSimRun11</id>
			<param01>3.0e+0</param01>
			<param02>9.0e+0</param02>
		</simdef>
	</simset>
	
	<sessionscript>
		<locationinfo>
			<userstaticdatafilepath>
				FULL_USERSTATICDATAFILE_DIRECTORY_GOES_HERE/userStaticData.ini
			</userstaticdatafilepath>
			<customdir>
				FULL_CUSTOM_DIRECTORY_GOES_HERE
			</customdir>
			<simspecdir>
				FULL_SIMSPEC_DIRECTORY_GOES_HERE
			</simspecdir>
			<resultsdir>
				FULL_RESULTS_DIRECTORY_GOES_HERE
			</resultsdir>
		</locationinfo>
		
		<machineset singlemachine="true" usedualkey="true" polldelay="21">
			<compilemachine>
				<infofile>MyCompileMachineInfoFile.json</infofile>
			</compilemachine>
			<standaloneserver>
				<infofile>MyServer01InfoFile.json</infofile>
				<numsimulators>4</numsimulators>
				<workdir>FULL_WORKING_DIRECTORY_HERE</workdir>
			</standaloneserver> 
		</machineset>
	</sessionscript>
	
</nmsession>
